Repository jmoiron/humanize, pull requests merged in 2020-06, with the labels that each got.

#131 Test Python 3.10-dev
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
Labels: testing

#134 Fix fractional(0.333) output in README
  README.md
  tests/test_number.py
Labels: bug, changelog: Fixed

#135 Fix incorrect Portuguese spelling
  src/humanize/locale/pt_BR/LC_MESSAGES/humanize.mo
  src/humanize/locale/pt_BR/LC_MESSAGES/humanize.po
Labels: bug, changelog: Fixed

#136 README: Update expected exception when translation not found
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  README.md
  setup.cfg
  tox.ini
Labels: changelog: skip, testing

#132 Explicit error if _DEFAULT_LOCALE_PATH is None
  src/humanize/i18n.py
Labels: bug, changelog: Fixed
