Repository jmoiron/humanize, pull requests merged in 2020-02, with the labels that each got.

#92 Move installable code to src/
  MANIFEST.in
  setup.py
  src/humanize/__init__.py
  src/humanize/compat.py
  src/humanize/filesize.py
  src/humanize/i18n.py
  src/humanize/locale/de_DE/LC_MESSAGES/humanize.mo
  src/humanize/locale/de_DE/LC_MESSAGES/humanize.po
  src/humanize/locale/fi_FI/LC_MESSAGES/humanize.mo
  src/humanize/locale/fi_FI/LC_MESSAGES/humanize.po
  src/humanize/locale/fr_FR/LC_MESSAGES/humanize.mo
  src/humanize/locale/fr_FR/LC_MESSAGES/humanize.po
  src/humanize/locale/id_ID/LC_MESSAGES/humanize.mo
  src/humanize/locale/id_ID/LC_MESSAGES/humanize.po
  src/humanize/locale/it_IT/LC_MESSAGES/humanize.mo
  src/humanize/locale/it_IT/LC_MESSAGES/humanize.po
  src/humanize/locale/ko_KR/LC_MESSAGES/humanize.mo
  src/humanize/locale/ko_KR/LC_MESSAGES/humanize.po
  src/humanize/locale/nl_NL/LC_MESSAGES/humanize.mo
  src/humanize/locale/nl_NL/LC_MESSAGES/humanize.po
  src/humanize/locale/pt_BR/LC_MESSAGES/humanize.mo
  src/humanize/locale/pt_BR/LC_MESSAGES/humanize.po
  src/humanize/locale/ru_RU/LC_MESSAGES/humanize.mo
  src/humanize/locale/ru_RU/LC_MESSAGES/humanize.po
  src/humanize/locale/sk_SK/LC_MESSAGES/humanize.mo
  src/humanize/locale/sk_SK/LC_MESSAGES/humanize.po
  src/humanize/locale/tr_TR/LC_MESSAGES/humanize.mo
  src/humanize/locale/tr_TR/LC_MESSAGES/humanize.po
  src/humanize/locale/vi_VI/LC_MESSAGES/humanize.mo
  src/humanize/locale/vi_VI/LC_MESSAGES/humanize.po
  src/humanize/locale/zh_CN/LC_MESSAGES/humanize.mo
  src/humanize/locale/zh_CN/LC_MESSAGES/humanize.po
  src/humanize/number.py
  src/humanize/time.py
  tox.ini
Labels: enhancement

#93 Update README
  MANIFEST.in
  README.md
  README.rst
  setup.py
Labels: enhancement

#94 Lint with tox and pre-commit on GitHub Actions
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  docs/conf.py
  setup.cfg
  setup.py
  src/humanize/__init__.py
  src/humanize/compat.py
  src/humanize/filesize.py
  src/humanize/i18n.py
  src/humanize/number.py
  src/humanize/time.py
  tests/base.py
  tests/test_filesize.py
  tests/test_number.py
  tests/test_time.py
  tox.ini
Labels: test

#95 Update setup and remove unused boilerplate docs
  MANIFEST.in
  docs/Makefile
  docs/_theme/nature/static/nature.css_t
  docs/_theme/nature/static/pygments.css
  docs/_theme/nature/theme.conf
  docs/conf.py
  docs/index.rst
  setup.cfg
  setup.py
  src/humanize/__init__.py
Labels: enhancement

#96 Turkish:some translation problems and typos are fixed
  src/humanize/locale/tr_TR/LC_MESSAGES/humanize.mo
  src/humanize/locale/tr_TR/LC_MESSAGES/humanize.po
Labels: translation

#98 Fix lint
  setup.cfg
  src/humanize/__init__.py
  tests/base.py
  tests/test_time.py
Labels: bug

#100 Move fa_IR translations to correct location
  setup.cfg
  src/humanize/__init__.py
  src/humanize/locale/fa_IR/LC_MESSAGES/humanize.mo
  src/humanize/locale/fa_IR/LC_MESSAGES/humanize.po
  tests/test_time.py
Labels: translation

#102 Drop support for EOL Python 2
  .pre-commit-config.yaml
  .travis.yml
  README.md
  pyproject.toml
  setup.cfg
  setup.py
  src/humanize/compat.py
  src/humanize/filesize.py
  src/humanize/i18n.py
  src/humanize/number.py
  src/humanize/time.py
  tests/base.py
  tests/test_filesize.py
  tests/test_i18n.py
  tests/test_number.py
  tests/test_time.py
  tox.ini
Labels: removal

#106 Revert "Allow 3.9-dev to fail"
  .travis.yml
Labels: test

#108 Refactor some tests to use pytest.mark.parametrize
  .gitignore
  tests/test_filesize.py
  tests/test_number.py
  tests/test_time.py
Labels: test

#109 Convert remaining tests to use pytest.mark.parametrize
  tests/base.py
  tests/test_time.py
Labels: test

#112 GHA: No need to repeat 'changelog' in the name and description
  .github/labels.yml
Labels: changelog: skip

#110 Add scientific notation to string support
  README.md
  src/humanize/__init__.py
  src/humanize/number.py
  tests/test_filesize.py
  tests/test_number.py
  tests/test_time.py
Labels: changelog: Added, enhancement

#114 Don't draft releases in forks
  .github/workflows/release-drafter.yml
  .pre-commit-config.yaml
Labels: changelog: skip

#115 Don't draft releases in forks
  .github/workflows/release-drafter.yml
Labels: changelog: skip

#107 Disambiguate naturaldate return: only append year if more than ~5 months away
  src/humanize/time.py
  tests/test_time.py
Labels: changelog: Changed, enhancement
