Repository jmoiron/humanize, pull requests merged in 2020-08, with the labels that each got.

#148 Deploy docs to Read the Docs
  .readthedocs.yml
  README.md
  docs/requirements.txt
  mkdocs.yml
  tox.ini
Labels: changelog: Added, documentation

#146 Improve default locale path discovering.
  src/humanize/i18n.py
  tests/test_i18n.py
Labels: changelog: Changed

#151 Drop support for Python 3.5
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  pyproject.toml
  setup.py
  src/humanize/number.py
  src/humanize/time.py
  tests/test_number.py
  tests/test_time.py
  tox.ini
Labels: changelog: Removed

#142 Update minimum_unit handling of naturaldelta and naturaltime
  src/humanize/time.py
  tests/test_time.py
Labels: changelog: Fixed
