Repository jmoiron/humanize, pull requests merged in 2020-11, with the labels that each got.

#176 Test Python 3.9 final on Travis CI
  .travis.yml
Labels: changelog: Changed, hacktoberfest-accepted, testing

#179 Remove Travis CI
  .github/workflows/test.yml
  .travis.yml
  README.md
  RELEASING.md
Labels: changelog: skip, testing

#178 Apply setup-py-upgrade
  .pre-commit-config.yaml
  pyproject.toml
  setup.cfg
  setup.py
Labels: changelog: Changed

#181 Fix grammar mistake in the Dutch translations
  src/humanize/locale/nl_NL/LC_MESSAGES/humanize.mo
  src/humanize/locale/nl_NL/LC_MESSAGES/humanize.po
Labels: bug, changelog: Fixed
