Repository jmoiron/humanize, pull requests merged in 2020-10, with the labels that each got.

#165 fix some translation for id_ID
  src/humanize/locale/id_ID/LC_MESSAGES/humanize.mo
  src/humanize/locale/id_ID/LC_MESSAGES/humanize.po
Labels: changelog: Added

#144 Allow custom "now" in naturaldelta and naturaltime
  .pre-commit-config.yaml
  src/humanize/time.py
  tests/test_time.py
Labels: enhancement

#168 testing/docs: Include doctests in testing
  src/humanize/filesize.py
  src/humanize/number.py
  src/humanize/time.py
  tox.ini
Labels: changelog: Added, testing

#170 Represent with a zero if the delta is too small
  src/humanize/time.py
  tests/test_time.py
Labels: bug

#171 Add initial support py3.9
  .github/workflows/test.yml
  setup.py
  tox.ini
Labels: changelog: Added, enhancement, hacktoberfest-accepted

#174 GHA: Temporarily toxlessly test PyPy
  .github/workflows/test.yml
Labels: changelog: skip, testing
