Repository jmoiron/humanize, pull requests merged in 2020-09, with the labels that each got.

#153 Update docs
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  docs/index.md
  setup.cfg
  src/humanize/__init__.py
  src/humanize/filesize.py
  src/humanize/i18n.py
  src/humanize/time.py
Labels: changelog: Fixed, documentation

#158 Add explicit setuptools dependency for pkg_resources
  setup.py
Labels: changelog: Added

#163 Internationalise a previously hardcoded 'and'
  src/humanize/i18n.py
  src/humanize/locale/de_DE/LC_MESSAGES/humanize.mo
  src/humanize/locale/de_DE/LC_MESSAGES/humanize.po
  src/humanize/locale/es_ES/LC_MESSAGES/humanize.po
  src/humanize/locale/fa_IR/LC_MESSAGES/humanize.po
  src/humanize/locale/fi_FI/LC_MESSAGES/humanize.mo
  src/humanize/locale/fi_FI/LC_MESSAGES/humanize.po
  src/humanize/locale/fr_FR/LC_MESSAGES/humanize.mo
  src/humanize/locale/fr_FR/LC_MESSAGES/humanize.po
  src/humanize/locale/id_ID/LC_MESSAGES/humanize.po
  src/humanize/locale/it_IT/LC_MESSAGES/humanize.po
  src/humanize/locale/ja_JP/LC_MESSAGES/humanize.po
  src/humanize/locale/ko_KR/LC_MESSAGES/humanize.po
  src/humanize/locale/nl_NL/LC_MESSAGES/humanize.mo
  src/humanize/locale/nl_NL/LC_MESSAGES/humanize.po
  src/humanize/locale/pl_PL/LC_MESSAGES/humanize.po
  src/humanize/locale/pt_BR/LC_MESSAGES/humanize.mo
  src/humanize/locale/pt_BR/LC_MESSAGES/humanize.po
  src/humanize/locale/pt_PT/LC_MESSAGES/humanize.mo
  src/humanize/locale/pt_PT/LC_MESSAGES/humanize.po
  src/humanize/locale/ru_RU/LC_MESSAGES/humanize.mo
  src/humanize/locale/ru_RU/LC_MESSAGES/humanize.po
  src/humanize/locale/sk_SK/LC_MESSAGES/humanize.mo
  src/humanize/locale/sk_SK/LC_MESSAGES/humanize.po
  src/humanize/locale/tr_TR/LC_MESSAGES/humanize.po
  src/humanize/locale/uk_UA/LC_MESSAGES/humanize.po
  src/humanize/locale/vi_VI/LC_MESSAGES/humanize.po
  src/humanize/locale/zh_CN/LC_MESSAGES/humanize.po
  src/humanize/time.py
  tests/test_i18n.py
Labels: bug, changelog: Fixed
