Repository jmoiron/humanize, pull requests merged in 2021-11, with the labels that each got.

#235 Fix and add Russian and Ukrainian words
  src/humanize/locale/ru_RU/LC_MESSAGES/humanize.po
  src/humanize/locale/uk_UA/LC_MESSAGES/humanize.po
Labels: changelog: Added

#236 Specify pypy-3.8 on GHA
  .github/workflows/test.yml
Labels: testing, changelog: skip

#238 add da_DK language
  README.md
  src/humanize/locale/da_DK/LC_MESSAGES/humanize.po
Labels: changelog: Added

#240 Reinstate `VERSION` and deprecate
  README.md
  src/humanize/__init__.py
  tests/test_humanize.py
  tests/test_i18n.py
  tests/test_number.py
  tests/test_time.py
  tox.ini
Labels: changelog: Deprecated

#234 Deprecate private functions
  src/humanize/i18n.py
  src/humanize/number.py
  src/humanize/time.py
  tests/test_time.py
Labels: changelog: Deprecated

#243 Temporarily comment out to avoid warning during `import humanize`
  src/humanize/time.py
Labels: changelog: Fixed
