Repository jmoiron/humanize, pull requests merged in 2021-10, with the labels that each got.

#229 Update github CI test with python 3.10 for new release
  .github/workflows/test.yml
Labels: testing, changelog: skip, hacktoberfest-accepted

#227 Use importlib.metadata to get package version instead of pkg_resources.get_distribution to decrease memory consumption
  setup.cfg
  src/humanize/__init__.py
Labels: changelog: Changed, hacktoberfest-accepted

#230 Remove redundant --max-py-version=3.10 from pre-commit
  .pre-commit-config.yaml
Labels: testing, changelog: skip, hacktoberfest-accepted

#231 Update release checklist to use python-build
  RELEASING.md
Labels: changelog: skip, documentation

#233 Add Traditional Chinese (zh-HK)
  .gitignore
  src/humanize/locale/zh_HK/LC_MESSAGES/humanize.po
Labels: changelog: Added, hacktoberfest-accepted

#182 Add missing strings for Polish translation
  src/humanize/locale/pl_PL/LC_MESSAGES/humanize.po
Labels: changelog: Added, hacktoberfest-accepted
