Repository jmoiron/humanize, pull requests merged in 2021-04, with the labels that each got.

#192 Add Catalan translation
  README.md
  src/humanize/locale/ca_ES/LC_MESSAGES/humanize.po
Labels: changelog: Added, enhancement

#195 Fix tests for Python 3.10
  .pre-commit-config.yaml
  setup.cfg
  src/humanize/time.py
Labels: bug, changelog: Fixed, testing

#196 Add documentation and release notes to project_urls
  .github/workflows/labels.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  setup.cfg
  src/humanize/number.py
  tox.ini
Labels: changelog: Changed, documentation

#197 Add Catalan binary translation
  src/humanize/locale/ca_ES/LC_MESSAGES/humanize.mo
Labels: changelog: Fixed

#199 Remove generated translation binaries from repo
  .github/workflows/test.yml
  .gitignore
  MANIFEST.in
  README.md
  RELEASING.md
  scripts/generate-translation-binaries.sh
  src/humanize/locale/ca_ES/LC_MESSAGES/humanize.mo
  src/humanize/locale/de_DE/LC_MESSAGES/humanize.mo
  src/humanize/locale/es_ES/LC_MESSAGES/humanize.mo
  src/humanize/locale/fa_IR/LC_MESSAGES/humanize.mo
  src/humanize/locale/fi_FI/LC_MESSAGES/humanize.mo
  src/humanize/locale/fr_FR/LC_MESSAGES/humanize.mo
  src/humanize/locale/id_ID/LC_MESSAGES/humanize.mo
  src/humanize/locale/it_IT/LC_MESSAGES/humanize.mo
  src/humanize/locale/ja_JP/LC_MESSAGES/humanize.mo
  src/humanize/locale/ko_KR/LC_MESSAGES/humanize.mo
  src/humanize/locale/nl_NL/LC_MESSAGES/humanize.mo
  src/humanize/locale/pl_PL/LC_MESSAGES/humanize.mo
  src/humanize/locale/pt_BR/LC_MESSAGES/humanize.mo
  src/humanize/locale/pt_PT/LC_MESSAGES/humanize.mo
  src/humanize/locale/ru_RU/LC_MESSAGES/humanize.mo
  src/humanize/locale/sk_SK/LC_MESSAGES/humanize.mo
  src/humanize/locale/tr_TR/LC_MESSAGES/humanize.mo
  src/humanize/locale/uk_UA/LC_MESSAGES/humanize.mo
  src/humanize/locale/vi_VI/LC_MESSAGES/humanize.mo
  src/humanize/locale/zh_CN/LC_MESSAGES/humanize.mo
  tests/test_i18n.py
Labels: changelog: Changed

#200 Add intword processing for thousands
  src/humanize/number.py
  tests/test_number.py
Labels: changelog: Changed, enhancement

#201 Update translation .po files with 'thousand'
  src/humanize/locale/ca_ES/LC_MESSAGES/humanize.po
  src/humanize/locale/de_DE/LC_MESSAGES/humanize.po
  src/humanize/locale/es_ES/LC_MESSAGES/humanize.po
  src/humanize/locale/fa_IR/LC_MESSAGES/humanize.po
  src/humanize/locale/fi_FI/LC_MESSAGES/humanize.po
  src/humanize/locale/fr_FR/LC_MESSAGES/humanize.po
  src/humanize/locale/id_ID/LC_MESSAGES/humanize.po
  src/humanize/locale/it_IT/LC_MESSAGES/humanize.po
  src/humanize/locale/ja_JP/LC_MESSAGES/humanize.po
  src/humanize/locale/ko_KR/LC_MESSAGES/humanize.po
  src/humanize/locale/nl_NL/LC_MESSAGES/humanize.po
  src/humanize/locale/pl_PL/LC_MESSAGES/humanize.po
  src/humanize/locale/pt_BR/LC_MESSAGES/humanize.po
  src/humanize/locale/pt_PT/LC_MESSAGES/humanize.po
  src/humanize/locale/ru_RU/LC_MESSAGES/humanize.po
  src/humanize/locale/sk_SK/LC_MESSAGES/humanize.po
  src/humanize/locale/tr_TR/LC_MESSAGES/humanize.po
  src/humanize/locale/uk_UA/LC_MESSAGES/humanize.po
  src/humanize/locale/vi_VI/LC_MESSAGES/humanize.po
  src/humanize/locale/zh_CN/LC_MESSAGES/humanize.po
Labels: changelog: Changed
